export const CREATE_CASESTUDY_REQUEST = "CREATE_CASESTUDY_REQUEST";
export const CREATE_CASESTUDY_SUCCESS = "CREATE_CASESTUDY_SUCCESS";
export const CREATE_CASESTUDY_FAIL = "CREATE_CASESTUDY_FAIL";

export const GET_CASESTUDIES_REQUEST = "GET_CASESTUDIES_REQUEST";
export const GET_CASESTUDIES_SUCCESS = "GET_CASESTUDIES_SUCCESS";
export const GET_CASESTUDIES_FAIL = "GET_CASESTUDIES_FAIL";

export const GET_SINGLE_CASESTUDY_REQUEST = "GET_SINGLE_CASESTUDY_REQUEST";
export const GET_SINGLE_CASESTUDY_SUCCESS = "GET_SINGLE_CASESTUDY_SUCCESS";
export const GET_SINGLE_CASESTUDY_FAIL = "GET_SINGLE_CASESTUDY_FAIL";

export const UPDATE_CASESTUDY_REQUEST = "UPDATE_CASESTUDY_REQUEST";
export const UPDATE_CASESTUDY_SUCCESS = "UPDATE_CASESTUDY_SUCCESS";
export const UPDATE_CASESTUDY_FAIL = "UPDATE_CASESTUDY_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
